version: '3'
services:

  postgresql:
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_14
    networks:
      - app-network
    volumes:
      - "my-data:/var/lib/postgresql/data"
    image: postgres

  app-sopimart:
    container_name: sopimart-com.app
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - SERVER_PORT=8080
      - DB_NAME=db_14
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DIRECTORY_PATH=/home
    ports:
      - "8082:8080"
    build: .
    networks:
      - app-network

volumes:
  my-data:
networks:
  app-network:
    driver: bridge